/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: dist/themes/gothic/gothicTheme.js
 * Command: astryx theme build dist/themes/gothic/gothicTheme.js --out src/themes/gothic/gothicTheme.css
 * Generated: 2026-07-23T20:42:51.202Z
 */

import type { DefinedTheme } from "@astryxdesign/core/theme";
import type { IconRegistry } from "@astryxdesign/core/Icon";
export declare const gothicIconRegistry: IconRegistry;
export declare const gothicTheme: DefinedTheme;
