name: Check tests for Broker

on:
  push:
    paths:
      - broker/**
      - .github/workflows/check-tests-broker.yml
  pull_request:
    paths:
      - broker/**
      - .github/workflows/check-tests-broker.yml

permissions:
  contents: read

jobs:
  test:
    name: Check tests for Broker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: broker
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: broker/.node-version
          cache: npm
          cache-dependency-path: broker/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
